package com.chen.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStdlb<M extends BaseStdlb<M>> extends Model<M> implements IBean {

	public void setID(Integer ID) {
		set("ID", ID);
	}

	public Integer getID() {
		return get("ID");
	}

	public void setNAME(String NAME) {
		set("NAME", NAME);
	}

	public String getNAME() {
		return get("NAME");
	}

	public void setNOTE(String NOTE) {
		set("NOTE", NOTE);
	}

	public String getNOTE() {
		return get("NOTE");
	}

}
