package com.chen.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStxxb<M extends BaseStxxb<M>> extends Model<M> implements IBean {

	public void setID(Integer ID) {
		set("ID", ID);
	}

	public Integer getID() {
		return get("ID");
	}

	public void setSTLB(Integer STLB) {
		set("STLB", STLB);
	}

	public Integer getSTLB() {
		return get("STLB");
	}

	public void setSTDL(Integer STDL) {
		set("STDL", STDL);
	}

	public Integer getSTDL() {
		return get("STDL");
	}

	public void setSTLX(Integer STLX) {
		set("STLX", STLX);
	}

	public Integer getSTLX() {
		return get("STLX");
	}

	public void setSTTM(String STTM) {
		set("STTM", STTM);
	}

	public String getSTTM() {
		return get("STTM");
	}

	public void setIMAGE(String IMAGE) {
		set("IMAGE", IMAGE);
	}

	public String getIMAGE() {
		return get("IMAGE");
	}

	public void setXXA(String XXA) {
		set("XXA", XXA);
	}

	public String getXXA() {
		return get("XXA");
	}

	public void setXXB(String XXB) {
		set("XXB", XXB);
	}

	public String getXXB() {
		return get("XXB");
	}

	public void setXXC(String XXC) {
		set("XXC", XXC);
	}

	public String getXXC() {
		return get("XXC");
	}

	public void setXXD(String XXD) {
		set("XXD", XXD);
	}

	public String getXXD() {
		return get("XXD");
	}

	public void setZQDA(String ZQDA) {
		set("ZQDA", ZQDA);
	}

	public String getZQDA() {
		return get("ZQDA");
	}

	public void setSTJX(String STJX) {
		set("STJX", STJX);
	}

	public String getSTJX() {
		return get("STJX");
	}

}
