package com.chen.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCjd<M extends BaseCjd<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setIdCard(String idCard) {
		set("id_card", idCard);
	}

	public String getIdCard() {
		return get("id_card");
	}

	public void setPhoto1(String photo1) {
		set("photo1", photo1);
	}

	public String getPhoto1() {
		return get("photo1");
	}

	public void setMark(Integer mark) {
		set("mark", mark);
	}

	public Integer getMark() {
		return get("mark");
	}

	public void setRegtime(String string) {
		set("regtime", string);
	}

	public String getRegtime() {
		return get("regtime");
	}

}
